name: "Python Container Action for BIOPYPIR"
description: "Do something simple"
author: "Ben Stear"
inputs: {}
#  myOUTPUT:
#    description: "Test result"
#   myExitCode:
#     description: "Exit code"
     
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: 'anchor'  
  color: 'green'
