name: "Python Container Action for BIOPYPIR"
description: "Do something simple"
author: "Ben Stear"
inputs:
  myrepo:
    description: "name of your repo"
    required: true
    default: ${{ github.repository }}
outputs:
  myOUTPUT:
    description: "Test result"
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: 'anchor'  
  color: 'green'
